test: add unit test about jobset controller
kubernetes-sigs/jobset pull request #473
Opened 2024-03-23 08:43 UTC by googs1025

Hello everyone, when I was studying the project, I found that the degree of unit testing was a bit low. I tried to add some unit testing code, hoping to help the project.
Add some unit tests about jobset controller. Improve overall unit test coverage

2024-03-23 13:52 UTC, kannon92 commented
/ok-to-test
/cc

2024-03-25 05:41 UTC, danielvegamyhre requested changes

2024-03-25 11:17 UTC, googs1025 commented on pkg/controllers/jobset_controller_test.go
> +			if diff := cmp.Diff(tc.expected, actual); diff != "" {
Thank your review. Indeed, in the test cases, the robustness of the code was not taken into consideration. At that time, I only focused on whether the methods had exceptions.

2024-03-25 11:19 UTC, googs1025 commented on pkg/controllers/jobset_controller_test.go
> +			if diff := cmp.Diff(tc.expected, actual); diff != "" {
I will take your suggestions into account and make code modifications. Thank you for your advice.

2024-03-26 00:57 UTC, googs1025 commented
@danielvegamyhre Hello, thank you for your suggestion. What I'm thinking is that currently, there are quite a few methods that need unit testing. Can I raise an issue to track them and submit multiple pull requests? This way, it will be easier for the reviewers as well. I will close this pull request and submit a new issue to track the progress.

2024-03-26 03:40 UTC, danielvegamyhre commented
> @danielvegamyhre Hello, thank you for your suggestion. What I'm thinking is that currently, there are quite a few methods that need unit testing. Can I raise an issue to track them and submit multiple pull requests? This way, it will be easier for the reviewers as well. I will close this pull request and submit a new issue to track the progress.

Yes that would be great

2024-03-26 03:59 UTC, closed without merging